### ISSUE TITLE
couldnt update msys2

### ISSUE THREAD

**Issue by hazemimam** [N00byKing/SM64AP-Launcher#2]
hello, i tried to use check dependences it said my msys2 path is correct but when it checks the dependences it says couldnt update msys2 any help?

**Comment by N00byKing** [comment]
- Provide a log file
- Something that is often reported is antivirus issues, please check that it didnt delete anything
- Try reinstalling msys, it likes to get corrupt sometimes

**Comment by hazemimam** [comment]
i tried reinstalling msys 2 in a diff place and that worked
